networks:
  npm_containers:
    external: true
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    networks:
      - npm_containers
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    ports:
      - ${WEBPORT}:80
    environment:
      - TZ=${TZ}
    user: "${UUID}:${GUID}"
    labels:
      - homepage.group=${HOMEPAGEGROUP}
      - homepage.name=${HOMEPAGENAME}
      - homepage.icon=${HOMEPAGEICON}
      - homepage.href=${HOMEPAGEHREF}
      - homepage.description=${HOMEPAGEDESCRIPTION}
    volumes:
      - ${VOLUMEROOT}:/srv:rw
      - ${VOLUMEROOT}/filebrowser/database:/database:rw
      - ${VOLUMEROOT}filebrowser/config:/config:rw
    restart: unless-stopped